### ISSUE TITLE
Wrap PsiPolyadicExpression in UAST

### ISSUE THREAD

**Issue by yole** [JetBrains/uast#11]
Instead of a chain of nested binary expressions, it should become a single UAST node.

**Comment by tnorbye** [comment]
Thanks for fixing this!

In Psi, PsiBinaryExpression extends PsiPolyadicExpression.
That's not the case for UAST (UBinaryExpression does not extend UPolyadicExpression -- interface UBinaryExpression : UExpression). 

Shouldn't it?

**Comment by 4u7** [comment]
I think it should, thank you!
