### ISSUE TITLE
Add getFunctionalInterfaceType to ULambdaExpression

### ISSUE THREAD

**Issue by tnorbye** [JetBrains/uast#16]
PsiLambdaExpression (and its parent class, PsiFunctionalExpression) provides this:

    @Nullable
    PsiType getFunctionalInterfaceType();

This is pretty useful; I'd like to be able to call something like this on ULambdaExpression as well. Can it be passed through from JavaULambdaExpression.kt (which is backed by a PsiLambdaExpression), and then the Kotlin side of things too -- KotlinULambdaExpression, though I'm not sure if it's easy/possible to get the same info there.

Here's an example of where I'like this:
    private OnTouchListener myListener = (v, event) -> v.performContextClick();

here the getFunctionalInterfaceType is OnTouchListener.

**Comment by 4u7** [comment]
Fixed with c3679a229383a303c59a7028c6961859732318f7
