### ISSUE TITLE
UObjectLiteralExpression is a call but doesn't visit argument list

### ISSUE THREAD

**Issue by tnorbye** [JetBrains/uast#17]
The UObjectLiteralExpression visit method does not seem to be visiting the argument list. UObjectLiteralExpression extends UCallExpression, which normally visits the methodIdentifier and valueArguments, but in UObjectLiteralExpression's visit it only visits the annotations and the class.

This is the root cause for this bug in Android Lint: 
https://issuetracker.google.com/issues/38073259

This happens because in the following code snippet, the argument list (referencing the R.layout.scout_template_spinner_item) is never seen by a visitor of the AST:

        mAdapter = new FirebaseRecyclerAdapter<String, SpinnerItemViewHolder>(
                String.class,
                R.layout.scout_template_spinner_item,
                SpinnerItemViewHolder.class,
                mRef) {
            @Override
            protected void populateViewHolder(SpinnerItemViewHolder viewHolder,
             ...

**Comment by SUPERCILEX** [comment]
Tracked here too: https://youtrack.jetbrains.com/issue/IDEA-172643

**Comment by yole** [comment]
Fixed in https://github.com/JetBrains/intellij-community/commit/d86a1d47261a6f1e660e66109b0f105e0437ebf3
