### ISSUE TITLE
Implement UVariable.typeReference for Kotlin local variables

### ISSUE THREAD

**Issue by yole** [JetBrains/uast#8]
The visitor needs to visit all type references. Right now it can't because trying to obtain a type reference for a Kotlin variable hits an unimplemented method UastKotlinPsiVariable.getTypeElement().

By the way, it doesn't seem necessary to implement KotlinULocalVariable on top of LightVariableBuilder. As a local PSI element, it should wrap the underlying KtProperty directly, and doesn't need to implement any Java PSI interfaces such as PsiVariable.

**Comment by 4u7** [comment]
Fixed by https://github.com/JetBrains/kotlin/commit/107879a78a7b54143ca27098b9d4c6e6f42c8bc8
